```sql
CREATE TABLE endereco (
        id INT AUTO_INCREMENT PRIMARY KEY,
        rua VARCHAR(255) NOT NULL,
        numero INT NOT NULL,
        bairro VARCHAR(255) NOT NULL,
        cidade VARCHAR(255) NOT NULL,
        estado VARCHAR(2) NOT NULL,
        cep VARCHAR(10) NOT NULL
);

Insert into endereco (rua, numero, bairro, cidade, estado, cep) values ('Rua 1', 123, 'Bairro 1', 'Cidade 1', 'SP', '12345-678');

Insert into endereco (rua, numero, bairro, cidade, estado, cep) values 
('Avenida Assembléia de Deus Ministério do Belém', NULL, '', 'Caieiras', 'SP', '07700-240'),
('Avenida dos Estudantes', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-625'),
('Avenida Doutor Armando Pinto', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-175'),
('Avenida Doutor Olindo Dártora', 398, '', 'Caieiras', 'SP', '07700-230'),
('Avenida João Martins Ramos', NULL, '', 'Caieiras', 'SP', '07700-250'),
('Avenida Lourides Dell Porto', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-610'),
('Avenida Manoel Carlos Gomes', NULL, '', 'Caieiras', 'SP', 'ver todos'),
('Avenida Presidente Kennedy', NULL, '', 'Caieiras', 'SP', 'ver todos'),
('Avenida Professor Carvalho Pinto', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-210'),
('Avenida Quatorze de Dezembro', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-170'),
('Avenida Valdemar Gomes Marino', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-001'),
('Passagem Joaquim Antonio', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-045'),
('Praça Antonio Siqueira', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-205'),
('Praça Maestro Francisco Assis Fernandes', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-070'),
('Praça Santo Antônio', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-177'),
('Rua Albert Hanser', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-605'),
('Rua Amleto Ricciarelli', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-690'),
('Rua Ângelo Bochini', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-165'),
('Rua Antonio Generoso da Silva', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-195'),
('Rua Antonio Pereira da Cruz', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-180'),
('Rua Argentina', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-620'),
('Rua Aziz Fackri', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-145'),
('Rua Bolívia', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-685'),
('Rua Brasil', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-645'),
('Rua Canadá', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-710'),
('Rua Capitão Alberto Graff', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-650'),
('Rua Chile', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-680'),
('Rua Curumim', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-700'),
('Rua Domingos do Carmo Leite', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-150'),
('Rua Dona Ambrosina do Carmo Buonaguide', NULL, '', 'Caieiras', 'SP', 'ver todos'),
('Rua Espanha', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-725'),
('Rua Eugênio Bertti', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-155'),
('Rua Flávio Augusto de Moraes', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-600'),
('Rua França', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-715'),
('Rua Guadalajara', NULL, '', 'Caieiras', 'SP', 'ver todos'),
('Rua Inglaterra', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-720'),
('Rua Irmã Noemi', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-190'),
('Rua Itália', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-640'),
('Rua João Dártora', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-005'),
('Rua João XXIII', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-185'),
('Rua José do Carmo Leite', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-130'),
('Rua José Rubens Peres', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-675'),
('Rua Luiz Celso Berti', NULL, '', 'Caieiras', 'SP', '07713-002'),
('Rua Manoel Gaspar', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-200'),
('Rua Mário Spera', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-120'),
('Rua México', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-630'),
('Rua Osvaldo de Carvalho', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-160'),
('Rua Padre Aquiles Silvestre', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-615'),
('Rua Panamá', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-730'),
('Rua Paraguai', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-670'),
('Rua Portugal', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-660'),
('Rua Santa Cecília', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-080'),
('Rua Santa Clara', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-010'),
('Rua Santa Rita', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-015'),
('Rua Santo Agostinho', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-040'),
('Rua Santo Antonio', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-050'),
('Rua São Benedito', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-095'),
('Rua São Cristovão', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-025'),
('Rua São Francisco', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-075'),
('Rua São João', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-020'),
('Rua São José', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-085'),
('Rua São Luiz', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-105'),
('Rua São Paulo', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-100'),
('Rua São Pedro', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-035'),
('Rua São Vicente', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-030'),
('Rua Uruguai', NULL, 'Jd Sto Antonio', 'Caieiras', 'SP', '07700-665'),
('Travessa Armando Minuchi', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-055'),
('Travessa Jornalista Francisco Peres', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-090'),
('Travessa José Batista da Cunha', NULL, 'Jd S Francisco', 'Caieiras', 'SP', '07700-065'),
('Travessa São Tomé', NULL, 'Lot Cresciúma', 'Caieiras', 'SP', '07700-125');
